pointdevente_index:
    path:     /
    defaults: { _controller: "HTMStockBundle:PointDeVente:index" }
    methods:  GET

pointdevente_show:
    path:     /{id}/show
    defaults: { _controller: "HTMStockBundle:PointDeVente:show" }
    methods:  GET

pointdevente_new:
    path:     /new
    defaults: { _controller: "HTMStockBundle:PointDeVente:new" }
    methods:  [GET, POST]

pointdevente_edit:
    path:     /{id}/edit
    defaults: { _controller: "HTMStockBundle:PointDeVente:edit" }
    methods:  [GET, POST]

pointdevente_delete:
    path:     /{id}/delete
    defaults: { _controller: "HTMStockBundle:PointDeVente:delete" }
    methods:  DELETE
