<?php

namespace HTM\StockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fournisseurRepository extends EntityRepository
{
}
