<?php

namespace HTM\StockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SalePointProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalePointProductRepository extends EntityRepository
{

    public function liste($produit, $user)
    {
        $qb = $this->createQueryBuilder('s')
            ->leftJoin('s.salePoint', 'sa')->addSelect('sa')
            ->Where('sa.magasinier = :ma')->setParameter('ma', $user)
            ->orderBy('s.id', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
