<?php

namespace Proxies\__CG__\HTM\StockBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Fournisseur extends \HTM\StockBundle\Entity\Fournisseur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'id', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'nom', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'prenom', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'adresse', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'tel', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'sexe', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'nomSociete', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'user', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'produitFournisseur');
        }

        return array('__isInitialized__', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'id', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'nom', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'prenom', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'adresse', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'tel', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'sexe', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'nomSociete', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'user', '' . "\0" . 'HTM\\StockBundle\\Entity\\Fournisseur' . "\0" . 'produitFournisseur');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Fournisseur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', array($tel));

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', array());

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', array($sexe));

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', array());

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomSociete($nomSociete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomSociete', array($nomSociete));

        return parent::setNomSociete($nomSociete);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomSociete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomSociete', array());

        return parent::getNomSociete();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\HTM\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduitFournisseur(\HTM\StockBundle\Entity\ProduitFournisseur $produitFournisseur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduitFournisseur', array($produitFournisseur));

        return parent::addProduitFournisseur($produitFournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduitFournisseur(\HTM\StockBundle\Entity\ProduitFournisseur $produitFournisseur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduitFournisseur', array($produitFournisseur));

        return parent::removeProduitFournisseur($produitFournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduitFournisseur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduitFournisseur', array());

        return parent::getProduitFournisseur();
    }

}
