security:
    providers:
        fos_userbundle:
            id: fos_user.user_manager
    role_hierarchy:
            ROLE_ADMIN:      ROLE_USER
            ROLE_SUPERADMIN: ROLE_ADMIN
            ROLE_MAGASINIER: ROLE_MAGASINIER
    firewalls:
        main:
            pattern:      .*
            form_login:
                provider:       fos_userbundle
                login_path:     /HTM/login
                use_forward:    
                check_path:     /HTM/login_check
                failure_path:   
                default_target_path: /HTM
            logout:
                path:   /HTM/logout
                target: /HTM
            anonymous:    true



    access_control:
        # Liste des pages accessibles à tous les utilisateurs (ne pas toucher)
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resseting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
        - { path: ^/HTM/magasinier/, role: ROLE_MAGASINIER }
        
        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
        - { path: ^/HTM/change-password, role: ROLE_USER }

        # PAGES ACCESSIBLES À TOUS
        - { path: ^/HTM.*, role: IS_AUTHENTICATED_ANONYMOUSLY }